### ISSUE TITLE
Definition of quasigroup is wrong

### ISSUE THREAD

**Issue by runKleisli** [idris-hackers/idris-algebra#3]
The definition of quasigroup posed says that a quasigroup can be determined by a type `a`, a binary operation `op : a -> a -> a` and two unary operations `rinverse, linverse : a -> a`.

Supposing `op` refers to the operation of a quasigroup on `a`, and `rinverse, linverse` refer to left and right division, the definition is wrong - for fixed `y`, there is no single `y' : a` such that `(x : a) -> (x y) y' = x`.

Now, suppose each `x : a` is identified with the left translation permutation L(_y_) : _r_ ↦ _yr_ of some _y_ in _b_ where _b_ is a quasigroup in the sense above. Then although L(_y_) determines the inverse permutation of L(_y_), to say that `op` is composition of permutations and each L(_y_) such that _y_ is in _b_ is given by some inhabitant of _a_ is, assuming _a_ is the least such type closed under `op` as the type of `op` implies, to say that _a_ = LMlt(_b_). But LMlt(_b_) does not determine _b_ -- in fact, for most 5-element loops _b_, LMlt(_b_) contains every permutation on 5 elements, and therefore without knowing naming scheme of LMlt(_b_) elements relative to elements of _b_ (the map _b_ → LMlt(_b_), _x_ ↦ L(_x_)), _b_ cannot be determined up to isomorphism from the elements of LMlt(_b_), and moreover more than one isomorphism class of _b_ of order 5 has the property that it is possible to express the left permutations of each 5-element loop up to isomorphism as elements of _a_ = LMlt(_b_). Therefore knowing `a, op, linverse, rinverse` is not enough to know _b_ and therefore not enough data to define a quasigroup under the proposed assumptions.

These are the two obvious candidates for a collection of natural data to determine quasigroups from first principals. Note also that a left quasigroup (one with left division, as in _x_ (_x_ \ _y_) = _y_) is not necessarily a right quasigroup. So the three binary operations and the equations relating them are a minimal definition.

I suggest `qunder` for (`\`) and `qover` for (`/`), since `over` is associated with lenses.

**Comment by markuspf** [comment]
Thank you for the comment.

I wonder whether the lengthy explanation above could've been accompanied by a pull-request that remedies the situation.
